name: Codecov Action
description: Test results and coverage reporting for GitHub Actions

inputs:
  junit-xml-pattern:
    description: Glob pattern for finding JUnit XML files
    required: false
    default: './**/*.junit.xml'
  coverage-xml-pattern:
    description: Glob pattern for finding Coverage XML files (Clover format)
    required: false
    default: './**/clover.xml'
  token:
    description: GitHub token for API access and artifacts
    required: true
  base-branch:
    description: Base branch to compare results against
    required: false
    default: 'main'
  enable-tests:
    description: Enable test results reporting
    required: false
    default: 'true'
  enable-coverage:
    description: Enable coverage reporting
    required: false
    default: 'true'
  post-pr-comment:
    description: Post results as a PR comment (in addition to Job Summary)
    required: false
    default: 'false'

outputs:
  # Test outputs
  total-tests:
    description: Total number of tests run
  passed-tests:
    description: Number of passed tests
  failed-tests:
    description: Number of failed tests
  test-pass-rate:
    description: Percentage of tests that passed
  tests-added:
    description: Number of tests added compared to base branch
  tests-removed:
    description: Number of tests removed compared to base branch
  tests-fixed:
    description: Number of tests that changed from failing to passing
  tests-broken:
    description: Number of tests that changed from passing to failing
  
  # Coverage outputs
  line-coverage:
    description: Line coverage percentage
  branch-coverage:
    description: Branch coverage percentage
  coverage-change:
    description: Change in line coverage compared to base branch
  branch-coverage-change:
    description: Change in branch coverage compared to base branch
  coverage-improved:
    description: Whether coverage improved compared to base branch (true/false)

runs:
  using: node20
  main: dist/index.js