name: Codecov Action
description: Test results and coverage reporting for GitHub Actions

inputs:
  junit-xml-pattern:
    description: Glob pattern for finding JUnit XML files
    required: false
    default: './**/*.junit.xml'
  token:
    description: GitHub token for posting PR comments
    required: true

outputs:
  total-tests:
    description: Total number of tests run
  passed-tests:
    description: Number of passed tests
  failed-tests:
    description: Number of failed tests
  test-pass-rate:
    description: Percentage of tests that passed

runs:
  using: node20
  main: dist/index.js